### ISSUE TITLE
After slicing the data read by OpenCV, the result is incorrect.

### ISSUE THREAD

**Issue by lwzhaojun** [acai66/opencv_matching#4]
After slicing the data read by OpenCV, I was able to alleviate the error after continuous processing of numpy, but after processing about 10 graphs, the error continued.
My suspicion is that the memory layout and data pointers may change after the slicing operation.
This is my main operation:
`        roi_img = img[left_top_y:right_low_y,left_top_x:right_low_x]
        template_img = np.ascontiguousarray(templat_img)
        real_img = np.ascontiguousarray(roi_img)`
opencv-python-headless version: 4.6.0.66.
You can try the demo function for working with images. Please help me.

**Comment by acai66** [comment]
Can you provide a minimal example code to reproduce this bug?

**Comment by lwzhaojun** [comment]
[0521.zip](https://github.com/acai66/opencv_matching/files/15387773/0521.zip)
Of course! But I can't provide the data for some reason. Excuse me.

**Comment by lwzhaojun** [comment]
Re-analyzed, it is possible that when there were multiple matches, there was something that was not released. The speed of release is too slow.

**Comment by acai66** [comment]
I have already tested similar invocation methods and did not find any runtime issues.
[results.zip](https://github.com/acai66/opencv_matching/files/15392931/results.zip)

**Comment by lwzhaojun** [comment]
Thanks. I finded the answer of this error. There are two error:
 1.Used so file path should be the same as compiled so file path.
2.subpixel should be close down.
Thanks again for your timely help.

**Comment by lwzhaojun** [comment]
Thanks. I finded the answer of this error. There are two error:
 1.Used so file path should be the same as compiled so file path.
2.subpixel should be close down.
Thanks again for your timely help.
