### ISSUE TITLE
Using the shared object (.so) with Python on Linux

### ISSUE THREAD

**Issue by haghajani** [acai66/opencv_matching#5]
I am trying to use libtemplatematching_ctype.so in a python file but the matcher is not returning any results. I works perfectly with templatematching_ctype.dll but I am not able to run the same code on Linux using the shared object. I would really appreciate your help.

**Comment by acai66** [comment]
Try this: https://github.com/acai66/opencv_matching/issues/3#issuecomment-2119180289

**Comment by haghajani** [comment]
Thank you this solved my problem!
